@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ0cmFpbmVyX2lkIjozLCJleHAiOjE2NjI2ODY5Njh9.2fITqEyztlwnw3408elrBWiZoYKIcCUbla4F70N2tmY

### Pokemon Requests

### Pokemon Index
GET http://localhost:3000/pokemon.json
Authorization: Bearer {{jwt}}

### Pokemon Show
GET http://localhost:3000/pokemon/6.json
Authorization: Bearer {{jwt}}

### Pokemon Create
POST http://localhost:3000/pokemon.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "pokemon_name": "Pikachu",
  "trainer_id": 3
}

### Pokemon Update
PATCH http://localhost:3000/pokemon/6.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "pokemon_name": "Vulpix"
}

### Pokemon Destroy
DELETE http://localhost:3000/pokemon/6.json
Authorization: Bearer {{jwt}}

### User Requests

### Users create (signup)
POST http://localhost:3000/trainer.json
Content-Type: application/json

{
  "trainer": "Amanda",
  "email": "amanda@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "pat@test.com",
  "password": "password"
}